trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and Push Docker Image
  jobs:
  - job: Build
    displayName: Build
    steps:
    - checkout: self

    # Other build steps go here

    - task: Docker@2
      displayName: Build and Push
      inputs:
        command: 'buildAndPush'
        containerRegistry: 'myContainerRegistry'
        repository: 'myDockerImage'
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest

- stage: Deploy
  displayName: Deploy Docker Image
  jobs:
  - job: Deploy
    displayName: Deploy
    steps:
    - checkout: self

    # Other deployment steps go here

    - task: Docker@2
      displayName: Run
      inputs:
        command: 'run'
        containerRegistry: 'myContainerRegistry'
        repository: 'myDockerImage'
        imageName: 'myContainerRegistry/myDockerImage:latest'
        containerCommand: 'sh /path/to/startup/script.sh'
