apiVersion: v1
kind: Pod
metadata:
  name: mycmbox
spec:
  restartPolicy: Always
  containers:
  - name: mycmbox
    image: busybox
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi    
    command:
      - sleep
      - "3600"
    # env:
    #   - name: CITY
    #     valueFrom:
    #       configMapKeyRef:
    #         name: cm-example
    #         key: city
    envFrom:
      - configMapRef:
          name: cm-example

