apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: myhpa-hpa
  namespace: default
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myhpa-app
  metrics:
   - type: Resource
     resource:
       name: cpu
       target:
         type: Utilization
         averageUtilization: 70
   - type: Resource
     resource:
       name: memory
       #targetAverageValue: 250M
       target:
         type: AverageValue
         averageValue: 190Mi
  behavior:
    scaleDown: 
      policies: 
      - type: Pods
        value: 4
        periodSeconds: 60 
      - type: Percent
        value: 10 
        periodSeconds: 60
      selectPolicy: Min 
      stabilizationWindowSeconds: 60
    scaleUp: 
      policies:
      - type: Pods
        value: 5
        periodSeconds: 70
      - type: Percent
        value: 12 
        periodSeconds: 80
      selectPolicy: Max
      stabilizationWindowSeconds: 0